version: '3.8' # גרסת Docker Compose מומלצת

services:
  # שירות אפליקציית ה-Node.js
  node-app:
    # בונה את האימג' מתוך ה-Dockerfile שנמצא בתיקייה הנוכחית
    build: .
    ports:
      # מיפוי פורטים: "פורט מקומי במחשב שלך:פורט בתוך הקונטיינר"
      # האפליקציה ב-Node.js בתוך הקונטיינר מאזינה לפורט 3001
      - "3001:3001"
    environment:
      # הגדרת משתני סביבה עבור אפליקציית ה-Node.js
      # אלו יילקחו מקובץ ה-.env שלך (אם קיים)
      GREENAPI_ID: ${idInstance}
      GREENAPI_TOKEN: ${apiTokenInstance}
      # הגדרת ה-URI לחיבור למונגו DB
      # 'mongo' הוא שם השירות של מונגו בתוך רשת הדוקר קומפוז
      MONGO_URI: mongodb://mongo:27017/my-mongo
    depends_on:
      # מבטיח ששירות ה'mongo' יהיה במצב 'healthy' לפני ששירות ה'node-app' יופעל
      mongo:
        condition: service_healthy
    restart: always # מפעיל מחדש את הקונטיינר אם הוא קורס

  # שירות מונגו DB
  mongo:
    image: mongo:latest # משתמש באימג' האחרון של מונגו DB
    ports:
      # מיפוי פורטים: "פורט מקומי במחשב שלך:פורט בתוך הקונטיינר"
      # פורט ברירת המחדל של מונגו הוא 27017
      - "27017:27017"
    volumes:
      # שומר את נתוני המונגו בנפח (volume) קבוע
      # זה מבטיח שהנתונים לא יימחקו כשמורידים את הקונטיינר
      - mongo_data:/data/db
    restart: always # מפעיל מחדש את הקונטיינר אם הוא קורס
    # הוספת healthcheck - בדיקה שמונגו DB אכן מוכן לקבל חיבורים
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # זמן המתנה לפני תחילת הבדיקות

# הגדרת הנפח (volume) שבו יישמרו נתוני מונגו DB
volumes:
  mongo_data: {}